name: PR Sonarqube

on:
  pull_request:
    paths-ignore:
      - deployment/**
      - .vscode/**
      - README.md
      - lombok.config
      - .gitignore

      

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: test1
      shell: bash 
      run: echo "${{ github.head_ref }}"
    - name: test2
      shell: bash 
      run: echo "${{ github.event.pull_request.number }}"
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 13.0.1
    - name: Sonar Check
      env:
        EL_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn -B verify sonar:sonar -q -Dsonar.login=$EL_TOKEN -Dsonar.pullrequest.base=master -Dsonar.pullrequest.key=${{ github.event.pull_request.number }} -Dsonar.pullrequest.branch=${{ github.head_ref }}
